
function [n] = countRectanglesByFilledArea(BW,min,max)
% Count rectangles in a binary image 
filedArea = filterRegionsByFiledArea(BW);
n = sum(filedArea >= min & filedArea <= max);
end

function [areas] = filterRegionsByFiledArea(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 27-Oct-2025
%---------------------------------------------------------

BW_out = BW_in;

% Get properties.
properties = regionprops(BW_out, {'FilledArea'});

% extraire les valeurs numériques (retourne [] si aucune région)
areas = [properties.FilledArea];

end