function [maskedRGBImage] = createMaskedImage(imageRGB,thresholds)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 27-Oct-2025
%------------------------------------------------------


% Convert RGB image to chosen color space
I = imageRGB;

% Define thresholds for channel 1 based on histogram settings
channel1Min = thresholds(1);
channel1Max = thresholds(2);

% Define thresholds for channel 2 based on histogram settings
channel2Min = thresholds(3);
channel2Max = thresholds(4);

% Define thresholds for channel 3 based on histogram settings
channel3Min = thresholds(5);
channel3Max = thresholds(6);

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = imageRGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
